Repository FE-Ocean/who-be-go, pull requests merged in 2022-09, with the labels that each got.

#242 Fix: 1일 일때 날짜 0되는 오류 수정
  js/api/boxOfficeApi.js
  js/pages/chart.js
Labels: 🛠FIX, 🔴HIGH

#243 Fix: 날짜 수정
  js/api/boxOfficeApi.js
Labels: 🛠FIX, 🔴HIGH

#244 Refactor: BASE_URL 업데이트, 차트 ts 적용
  js/api/boxOfficeApi.js
  js/api/boxOfficeApi.ts
  js/api/movieApi.js
  js/api/movieApi.ts
  js/pages/chart.js
  js/pages/chart.ts
  js/url/BASE_URL.js
  js/url/BASE_URL.ts
Labels: 🧹REFACTOR

#247 Refactor: 기존 js 형식 데이터 파일 json 으로 변경
  movieData.json
Labels: 🛠FIX, 🧹REFACTOR
