Repository FE-Ocean/who-be-go, pull requests merged in 2022-08, with the labels that each got.

#3 Setting: SCSS 초기세팅 변경
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  html/footer.html
  html/nav.html
  package-lock.json
  package.json
  pages/siupUp.html
  styles/base/_reset.scss
  styles/components/buttons.css
  styles/components/buttons.scss
  styles/components/img-card.css
  styles/components/img-card.scss
  styles/main.css
  styles/main.scss
  styles/pages/_home.scss
  styles/pages/home.css
  styles/pages/home.scss
Labels: 📄DOCS

#7 Style: button UI 컴포넌트화
  styles/components/_buttons.scss
  styles/components/buttons.css
  styles/components/buttons.scss
  styles/components/img-card.css
  styles/components/img-card.scss
  styles/main.css
  styles/main.scss
Labels: 🎨DESIGN

#8 Feat: 독후감 작성 페이지 마크업 및 css 구현
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#13 Style: 클래스 이름 형식 수정
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#15 Setting: 스타일 추가 및 수정
  styles/base/_global.scss
  styles/base/_reset.scss
  styles/constants/_typography.scss
Labels: 🟢LOW, 🎨DESIGN

#17 Design: 페이지 css에서 body의 속성 삭제 및 하위 요소로 이동
  styles/main.css
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🟢LOW, 🎨DESIGN

#14 Feat: 헤더, 푸터 마크업 및 css 구현
  assets/icons/menu.svg
  html/common.html
  html/footer.html
  html/nav.html
  js/common.js
  styles/components/common.css
  styles/components/common.scss
Labels: 💡FEAT, 🎨DESIGN

#20 Design: 헤더/푸터 적용 및 placeholder에 폰트 적용
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🟡MEDIUM, 🎨DESIGN

#19 Feat: 모달 컴포넌트 마크업 및 css 구현
  html/modal.html
  styles/components/modal.css
  styles/components/modal.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#26 Feature: 헤더 로고 클릭시 메인페이지 이동 기능 추가
  html/common.html
  index.html
  js/common.js
  pages/writePost.html
Labels: 💡FEAT, 🛠FIX

#27 Feat: 영화 찾아요 페이지 마크업 및 css 작성
  index.html
  pages/search.html
  pages/writePost.html
  styles/pages/search.css
  styles/pages/search.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#31 Fix: id, class 명 수정 , 반응형 UI 적용
  index.html
  pages/siupUp.html
  styles/components/_card.scss
  styles/components/common.css
  styles/components/common.scss
  styles/main.css
  styles/pages/home.css
  styles/pages/home.scss
Labels: 💡FEAT, 🟢LOW, 🎨DESIGN

#36 Design: CSS 통일성있게 수정
  pages/signUp.html
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 🟢LOW, 🎨DESIGN

#35 Feat: 독후감 작성 시 이미지 업로드 기능 추가
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
Labels: 💡FEAT, 🔴HIGH

#39 Feat: 로그인 페이지 마크업 및 css 구현
  pages/login.html
  styles/pages/login.css
  styles/pages/login.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#40 Fix: 리뷰 길이에 따라 textarea의 높이가 조정되게 수정
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🛠FIX, 🟢LOW

#41 fix: home 페이지 마크업, CSS 수정
  index.html
  styles/components/_card.scss
  styles/main.css
Labels: 💡FEAT, 🟢LOW, 🎨DESIGN

#43 Fix: placeholder에서 미변경된 부분 수정
  pages/writePost.html
Labels: 🛠FIX, 🟢LOW

#46 Fix: common(헤더,푸터) 수정 작업
  html/common.html
  index.html
  js/common.js
  pages/search.html
  pages/writePost.html
  styles/components/common.css
  styles/components/common.scss
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN, ♻RENAME

#44 Feat: 영화검색결과 페이지 마크업 및 css 작성
  pages/searchResult.html
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#47 feature: 영화 차트 마크업 및 CSS
  index.html
  pages/chart.html
  styles/components/_card.scss
  styles/main.css
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#45 Feat: 호버 및 클릭 시 별점 바뀌는 기능 추가
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 💡FEAT, 🟢LOW, 🎨DESIGN

#48 Design: 회원가입 폼 CSS 개선
  pages/signUp.html
  styles/base/_reset.scss
  styles/constants/_colors.scss
  styles/main.css
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#51 Feature: notFound, Loading 페이지 마크업 및 CSS 작성
  pages/loading.html
  pages/notFound.html
  styles/components/common.css
  styles/components/common.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#53 Feat: 로그아웃 기능 추가
  html/modal.html
  index.html
  js/common.js
  pages/chart.html
  pages/loading.html
  pages/notFound.html
  pages/search.html
  pages/searchResult.html
  pages/writePost.html
  styles/components/common.css
  styles/components/modal.css
  styles/components/modal.scss
Labels: 💡FEAT, 🟡MEDIUM

#57 Design: 마이페이지에 필요한 공통 컴포넌트 CSS 추가
  styles/components/_buttons.scss
  styles/components/_card.scss
  styles/main.css
Labels: 🟢LOW, 🎨DESIGN

#60 Fix: 홈페이지, 영화차트 페이지 마크업 구조적으로 수정
  index.html
  pages/chart.html
Labels: 🛠FIX, 🟢LOW

#61 Feature: 리뷰 페이지 HTML,CSS 작업
  assets/icons/icon-more-vertical.svg
  pages/review.html
  styles/pages/review.css
  styles/pages/review.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#55 Design: 디자인 수정 및 푸터 추가
  assets/icons/icon-search.svg
  pages/search.html
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#56 Design: 디자인 수정 및 푸터 추가
  pages/searchResult.html
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#64 Feature: 프로필 설정 마크업 및 CSS 작성
  pages/signUp.html
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#65 Feature: 리뷰 상세 페이지 HTML, CSS 작업
  pages/reviewDetail.html
  styles/pages/reviewDetail.css
  styles/pages/reviewDetail.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#67 Fix: 로그아웃 기능 추가된 헤더로 수정, 모달 추가
  pages/myPage.html
  styles/components/_card.scss
  styles/main.css
Labels: 💡FEAT, 🟢LOW, 🎨DESIGN

#70 Fix: 감상문 작성 시 이미지 업로드 1장으로 제한
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
  styles/components/modal.css
  styles/main.css
  styles/pages/chart.css
  styles/pages/home.css
  styles/pages/login.css
  styles/pages/myPage.css
  styles/pages/search.css
  styles/pages/searchResult.css
  styles/pages/signUp.css
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🟢LOW, 🎨DESIGN

#74 Fix: 이미지 사이즈 10mb 미만으로 제한하도록 수정
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
Labels: 🛠FIX, 🟢LOW

#76 Design: 공통 요소들 main에 통합 및 디폴트 이미지 추가
  assets/images/post_default.jpg
  styles/components/_card.scss
  styles/components/_common.scss
  styles/components/_modal.scss
  styles/constants/_colors.scss
  styles/main.css
  styles/main.scss
Labels: 🟡MEDIUM, 🎨DESIGN

#78 Feature: 영화차트페이지 부제 추가, 컬러변수 적용, 마크업 수정
  pages/chart.html
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#84 Design: 감상문 작성 페이지의 디자인 수정
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🟢LOW, 🎨DESIGN

#86 Fix: 푸터 위치 조정
  html/common.html
  styles/components/_buttons.scss
  styles/components/_common.scss
  styles/pages/chart.css
  styles/pages/chart.scss
  styles/pages/home.css
  styles/pages/home.scss
  styles/pages/myPage.css
  styles/pages/myPage.scss
  styles/pages/search.css
  styles/pages/search.scss
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#87 Feature: 감상문 업로드 기능 추가
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
  tsconfig.json
Labels: 📡API, 💡FEAT, 🔴HIGH

#89 Fix: 영화감상문 Tab 경로수정, 리뷰페이지 UI 수정
  index.html
  pages/loading.html
  pages/myPage.html
  pages/notFound.html
  pages/review.html
  styles/base/_reset.scss
  styles/components/_modal.scss
  styles/main.css
  styles/pages/review.css
  styles/pages/review.scss
Labels: 🛠FIX, 🟢LOW

#94 Design: 리뷰 상세페이지 UI 수정 , 디폴트 이미지 변경
  assets/images/max_post_default.jpg
  assets/images/min-post-default.jpg
  assets/images/min_post_default.jpg
  assets/images/post_default.jpg
  pages/review.html
  pages/reviewDetail.html
  styles/components/_card.scss
  styles/main.css
  styles/pages/review.css
  styles/pages/review.scss
  styles/pages/reviewDetail.css
  styles/pages/reviewDetail.scss
Labels: 🟡MEDIUM, 🎨DESIGN

#92 Fix: 모달의 바깥 부분을 누르면 모달 창이 꺼지도록 수정
  js/common.js
Labels: 🛠FIX, 🟢LOW

#93 Fix: 버튼 disabled 클래스에 이벤트 방지 속성 추가 및 BASE_URL 분리
  js/BASE_URL.js
  js/writePost.js
  js/writePost.ts
  pages/writePost.html
  styles/components/_buttons.scss
Labels: 🛠FIX, 🟢LOW

#97 Feature: 리뷰상세 페이지 API 연동
  js/reviewDetail.js
  js/reviewDetail.ts
  pages/reviewDetail.html
Labels: 📡API, 💡FEAT, 🔴HIGH

#99 Fix: BASE_URL에 영화 api 주소 추가 및 import 에러 수정
  js/BASE_URL.js
  js/BASE_URL.ts
  js/writePost.js
  js/writePost.ts
Labels: 🛠FIX, 🟢LOW

#95 Feature: 리뷰리스트 기능 구현
  js/review.js
  js/review.ts
Labels: 📡API, 💡FEAT, 🔴HIGH

#101 Fix: API 포스터 사이즈에 맞춰 UI 수정, 마크업 수정
  index.html
  styles/components/_card.scss
  styles/main.css
  styles/pages/review.css
  styles/pages/review.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#100 Feature: 로그인 기능 구현
  js/login.js
  js/login.ts
  pages/login.html
Labels: 📡API, 💡FEAT, 🟡MEDIUM

#102 Fix: 내비게이션 바의 로그인 테스트 임시 코드 삭제
  js/common.js
  js/reviewDetail.ts
Labels: 🛠FIX, 🟡MEDIUM

#103 Fix: 글 작성 시 로컬 스토리지에서 토큰 받아오게 수정
  js/writePost.js
  js/writePost.ts
  styles/pages/writePost.css
Labels: 🛠FIX, 🟡MEDIUM

#104 Fix: 로컬스토리지에 accountname 저장
  js/login.js
  js/login.ts
Labels: 🛠FIX, 🟢LOW

#105 Feature: 사용자의 감상문을 받아오는 기능 및 누르면 상세 페이지로 이동하는 기능 추가
  js/postInterface.js
  js/postInterface.ts
  js/review.js
  js/review.ts
  js/reviewDetail.js
  js/reviewDetail.ts
  pages/review.html
  pages/reviewDetail.html
  styles/pages/review.scss
  styles/pages/reviewDetail.scss
Labels: 📡API, 💡FEAT, 🔴HIGH

#106 Fix: 리뷰 작성 후 그 리뷰의 상세 페이지로 가도록 수정
  js/writePost.js
  js/writePost.ts
Labels: 🛠FIX, 🟡MEDIUM

#107 Feature: 회원가입 페이지 유효성 검사 기능 구현
  js/signUp.js
  js/signUp.ts
  pages/signUp.html
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 💡FEAT, 🛠FIX, 🔴HIGH, 🎨DESIGN

#108 Fix: 로그아웃 시 로컬스토리지에서 accountname도 제거하도록 변경
  js/common.js
Labels: 🛠FIX, 🟢LOW

#109 Feature: 리뷰 삭제 기능 추가
  js/common.js
  js/review.js
  js/review.ts
  pages/review.html
Labels: 📡API, 💡FEAT, 🔴HIGH

#110 Feature: 검색 기능
  js/movieListInterface.js
  js/movieListInterface.ts
  js/search.js
  js/search.ts
  pages/search.html
  styles/pages/search.css
  styles/pages/search.scss
Labels: 📡API, 💡FEAT, 🔴HIGH

#114 Fix: 리뷰 작성 시 영어 부제목도 같이 보내도록 수정
  js/review.js
  js/review.ts
  js/reviewApi.js
  js/reviewDetail.js
  js/reviewDetail.ts
  js/reviewEdit.js
  js/reviewEdit.ts
  js/writePost.js
  js/writePost.ts
Labels: 🛠FIX, 🟢LOW

#116 Fix: 리뷰페이지에서 영화별점 수정, 기본 이미지 추가
  assets/icons/star-yellow-100.svg
  js/review.js
  js/review.ts
  styles/pages/review.css
  styles/pages/review.scss
Labels: 🛠FIX, 🟡MEDIUM

#118 Fix: 리뷰 상세 페이지에서도 수정/삭제되도록 수정
  js/reviewDetail.js
  js/reviewDetail.ts
  pages/reviewDetail.html
  styles/components/_modal.scss
  styles/main.css
Labels: 🛠FIX, 🔴HIGH

#120 Design: searchResult 디자인 수정 및 미디어쿼리 추가
  pages/searchResult.html
  styles/components/_card.scss
  styles/main.css
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 🟢LOW, 🎨DESIGN

#121 Fix: 리뷰상세 페이지 영화별점 변경
  js/review.js
  js/review.ts
  js/reviewDetail.js
  js/reviewDetail.ts
  pages/review.html
  pages/reviewDetail.html
  styles/pages/reviewDetail.css
  styles/pages/reviewDetail.scss
Labels: 🛠FIX, 🟡MEDIUM

#125 Feature: 프로필 설정 기능 구현
  js/signUp.js
  js/signUp.ts
  pages/signUp.html
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 📡API, 💡FEAT, 🔴HIGH

#123 Feature: 토큰 검증
  js/review.js
  js/review.ts
  js/tokenValid.js
  js/tokenValid.ts
Labels: 📡API, 💡FEAT, 🟡MEDIUM

#128 Feature: 영화 추천 기능 구현
  index.html
  js/BASE_URL.js
  js/BASE_URL.ts
  js/randomMovie.js
  js/randomMovie.ts
  js/randomMovieList.js
  js/randomMovieList.ts
  styles/components/_card.scss
  styles/main.css
Labels: 📡API, 💡FEAT, 🔴HIGH, 🎨DESIGN

#126 Fix: 리뷰 페이지에서 바깥 부분을 클릭 시 드롭박스 닫히도록 수정
  js/review.js
  js/review.ts
  styles/pages/review.css
  styles/pages/review.scss
Labels: 🛠FIX, 🟡MEDIUM

#129 Feature: 무한스크롤 구현
  js/review.js
  js/review.ts
  js/reviewApi.js
  js/reviewApi.ts
Labels: 📡API, 💡FEAT, 🟡MEDIUM

#130 Feature: 새로운 영화 추천 버튼 추가
  index.html
  styles/components/_buttons.scss
  styles/main.css
  styles/pages/home.css
  styles/pages/home.scss
Labels: 💡FEAT, 🟢LOW, 🎨DESIGN

#131 Design: 영화 추천 목록 추가 및 UI 수정
  js/randomMovie.js
  js/randomMovie.ts
  js/randomMovieList.js
  js/randomMovieList.ts
  styles/components/_card.scss
  styles/main.css
  styles/pages/home.css
  styles/pages/home.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#134 searchResult 페이지 완성
  js/search.js
  js/search.ts
  js/searchResult.js
  js/searchResult.ts
  pages/searchResult.html
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 📡API, 💡FEAT, 🔴HIGH, 🎨DESIGN

#135 Design: 줄거리 및 포스터 크기 수정
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 🟢LOW, 🎨DESIGN

#133 Feature: 영화차트페이지 API 사용해서 기능 구현
  js/chart.js
  pages/chart.html
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 📡API, 💡FEAT, 🔴HIGH

#137 Fix: 감상문 작성 시 검색 결과의 정보를 받아오도록 수정
  js/movieApi.js
  js/movieApi.ts
  js/searchResult.js
  js/searchResult.ts
  js/writePost.js
  js/writePost.ts
  pages/searchResult.html
Labels: 📡API, 🛠FIX, 🔴HIGH

#139 Refactor: 유저 관련 api 함수 개별 파일로 분리
  js/login.js
  js/login.ts
  js/signUp.js
  js/signUp.ts
  js/userApi.js
  js/userApi.ts
Labels: 🧹REFACTOR, 🟢LOW

#141 Fix: 영화 정보 불러올 때 movieId도 같이 검색하도록 수정
  js/movieApi.js
  js/movieApi.ts
  js/searchResult.js
  js/searchResult.ts
  js/writePost.js
  js/writePost.ts
Labels: 📡API, ☠BUG, 🛠FIX, 🔴HIGH

#144 Fix: 무한스크롤 수정
  js/review.js
  js/review.ts
Labels: ☠BUG, 🛠FIX, 🔴HIGH

#145 Feature: 영화 상세 페이지 정보들 예외처리 추가
  js/searchResult.js
  js/searchResult.ts
Labels: 💡FEAT, 🟡MEDIUM

#146 Fix: 영화 추천 오류 수정, 내용삽입 함수 별도 분리, 버튼 리프레시 수정
  index.html
  js/randomMovie.js
  js/randomMovie.ts
  js/randomMovieList.js
  js/randomMovieList.ts
Labels: ☠BUG, 🛠FIX, 🧹REFACTOR, 🟢LOW

#151 search 페이지 기능 수정 및 디자인 수정
  js/search.js
  js/search.ts
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#152 Feature: 회원가입 시 비밀번호 재확인 추가
  index.html
  js/signUp.js
  js/signUp.ts
  package.json
  pages/signUp.html
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 💡FEAT, 🟢LOW

#157 Feature: 일별박스오피스 개선
  js/chart2.js
  js/chart2.ts
  js/movieListInterface.js
  js/movieListInterface.ts
  pages/chart.html
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 📡API, 🛠FIX, 🔴HIGH

#148 Feature: 마이 페이지 구현
  js/myPage.js
  js/myPage.ts
  js/userApi.js
  js/userApi.ts
  pages/myPage.html
  styles/components/_card.scss
  styles/pages/myPage.scss
Labels: 📡API, 💡FEAT, 🔴HIGH

#155 searchResult 페이지 애니메이션 추가 및 상영정보 공란인 경우 처리
  js/searchResult.js
  js/searchResult.ts
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 💡FEAT, 🟢LOW, 🎨DESIGN

#158 Feature: 프로필 수정 기능 구현
  js/profileEdit.js
  js/profileEdit.ts
  js/signUp.js
  js/signUp.ts
  js/userApi.js
  js/userApi.ts
  pages/myPage.html
  pages/profileEdit.html
Labels: 📡API, 💡FEAT, 🔴HIGH

#159 Fix: type 추가
  js/profileEdit.js
  js/profileEdit.ts
Labels: 🛠FIX, 🟢LOW

#162 Fix: 검색 시 버그 수정
  js/search.js
  js/search.ts
  pages/search.html
Labels: 🛠FIX, 🟢LOW

#160 Design: UI 스크롤, 모달 등 기타 디테일 수정
  pages/review.html
  pages/reviewEdit.html
  pages/writePost.html
  styles/components/_card.scss
  styles/components/_common.scss
  styles/components/_modal.scss
  styles/constants/_colors.scss
  styles/main.css
  styles/pages/myPage.css
  styles/pages/myPage.scss
  styles/pages/review.css
  styles/pages/review.scss
  styles/pages/reviewDetail.css
  styles/pages/reviewDetail.scss
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🟢LOW, 🎨DESIGN

#163 Fix: 이미지 없는 글 수정 시 img 태그 안 보이도록 수정
  js/reviewEdit.js
  js/reviewEdit.ts
  pages/reviewEdit.html
Labels: ☠BUG, 🛠FIX, 🟡MEDIUM

#164 Fix: 헤더 수정
  assets/icons/logo-title-s.svg
  html/common.html
  index.html
  pages/chart.html
  pages/loading.html
  pages/myPage.html
  pages/notFound.html
  pages/review.html
  pages/reviewDetail.html
  pages/reviewEdit.html
  pages/search.html
  pages/searchResult.html
  pages/writePost.html
  styles/components/_common.scss
  styles/main.css
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#167 Feature: 로딩 중일 때 로딩 컴포넌트 추가
  index.html
  js/myPage.js
  js/myPage.ts
  js/profileEdit.js
  js/profileEdit.ts
  js/randomMovie.js
  js/randomMovie.ts
  js/review.js
  js/review.ts
  js/reviewDetail.js
  js/reviewDetail.ts
  js/reviewEdit.js
  js/reviewEdit.ts
  js/searchResult.js
  js/searchResult.ts
  js/writePost.js
  js/writePost.ts
  pages/myPage.html
  pages/profileEdit.html
  pages/review.html
  pages/reviewDetail.html
  pages/reviewEdit.html
  pages/searchResult.html
  pages/writePost.html
  styles/components/_common.scss
  styles/main.css
Labels: 💡FEAT, 🟡MEDIUM

#171 Fix: 마이 페이지에서 토큰 검증하도록 수정
  js/myPage.js
  js/myPage.ts
Labels: 🛠FIX, 🟡MEDIUM

#172 Bug: background-image 속성 사용으로 발생하는 버그 수정
  index.html
  js/profileEdit.js
  js/profileEdit.ts
  js/signUp.js
  js/signUp.ts
  pages/login.html
  pages/profileEdit.html
  pages/signUp.html
  styles/pages/myPage.css
  styles/pages/myPage.scss
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: ☠BUG, 🛠FIX, 🔴HIGH, 🎨DESIGN

#168 Fix: 차트페이지 카드 클릭시 상세페이지 이동 및 영화 랭킹 출력 작업
  js/chart2.js
  js/chart2.ts
  pages/chart.html
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 📡API, 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#173 Design: 차트페이지 UI 디자인 수정, 불필요한 코드 제거
  js/chart2.js
  js/chart2.ts
  js/randomMovie.js
  js/randomMovie.ts
  pages/chart.html
  styles/components/_card.scss
  styles/main.css
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 🟢LOW, 🎨DESIGN

#174 Refactor: 영화 관련 api 함수 개별 파일로 분리
  js/BASE_URL.js
  js/BASE_URL.ts
  js/boxOfiiceApi.js
  js/boxOfiiceApi.ts
  js/chart2.js
  js/chart2.ts
  js/movieApi.js
  js/movieApi.ts
  js/randomMovie.js
  js/randomMovie.ts
  js/search.js
  js/search.ts
  pages/search.html
Labels: 🧹REFACTOR, 🟢LOW

#175 Fix: 감상문 작성 페이지에서 토큰 검증하도록 수정
  js/writePost.js
  js/writePost.ts
Labels: 🛠FIX, 🟡MEDIUM

#179 Design: 파비콘 추가
  favicon.ico
  index.html
Labels: 🟡MEDIUM, 🎨DESIGN

#182 Fix: 감상문이 10개 미만일 시 무한 로딩되는 문제 수정
  js/review.js
  js/review.ts
Labels: ☠BUG, 🛠FIX, 🔴HIGH

#181 search 페이지 검색 결과 수정
  js/search.js
  js/search.ts
  pages/search.html
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#183 fix: getSearchResult 함수 url 수정
  js/movieApi.js
  js/movieApi.ts
Labels: ☠BUG, 🟢LOW

#185 Design: 검색페이지 UI 수정
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🟢LOW, 🎨DESIGN

#184 Fix: 영화 정보 받아오는 함수 통합
  js/boxOfiiceApi.js
  js/chart2.js
  js/chart2.ts
  js/imageApi.js
  js/login.js
  js/movieApi.js
  js/movieApi.ts
  js/myPage.js
  js/profileEdit.js
  js/randomMovie.js
  js/randomMovie.ts
  js/review.js
  js/reviewApi.js
  js/reviewDetail.js
  js/reviewEdit.js
  js/search.js
  js/searchResult.js
  js/searchResult.ts
  js/signUp.js
  js/tokenValid.js
  js/userApi.js
  js/writePost.js
  js/writePost.ts
  tsconfig.json
Labels: 🛠FIX, 🧹REFACTOR, 🔴HIGH

#176 Fix: 차트페이지 CSS 순서 정렬 및 코드 최적화
  js/chart2.js
  js/chart2.ts
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 🟢LOW, 🎨DESIGN

#187 Fix: movieApi 덜 바뀌었던 부분 수정
  js/movieApi.js
Labels: ☠BUG, 🛠FIX, 🔴HIGH

#188 Design: 다른 비율 포스터 표출 수정 및 애니메이션 추가
  pages/searchResult.html
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 🟢LOW, 🎨DESIGN

#192 Design: 푸터 마크업 추가, 헤더 크기 수정, 기타 UI 수정
  html/common.html
  html/modal.html
  index.html
  pages/chart.html
  pages/myPage.html
  pages/review.html
  pages/reviewDetail.html
  pages/reviewEdit.html
  pages/search.html
  pages/searchResult.html
  pages/writePost.html
  styles/components/_common.scss
  styles/components/_modal.scss
  styles/main.css
  styles/pages/chart.css
  styles/pages/chart.scss
  styles/pages/home.css
  styles/pages/home.scss
  styles/pages/myPage.css
  styles/pages/myPage.scss
  styles/pages/reviewDetail.css
  styles/pages/reviewDetail.scss
  styles/pages/search.css
  styles/pages/search.scss
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#193 Feature: 리뷰 작성/수정 시 이미지 삭제 기능 추가
  assets/icons/icon-close.svg
  js/reviewEdit.js
  js/reviewEdit.ts
  js/writePost.js
  js/writePost.ts
  pages/reviewEdit.html
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 💡FEAT, 🟡MEDIUM

#196 Fix: 충돌난 부분 수정
  pages/reviewEdit.html
  pages/writePost.html
  styles/pages/writePost.css
  styles/pages/writePost.scss
Labels: 🛠FIX, 🟢LOW, 🎨DESIGN

#194 Fix: 취소버튼 클릭시 index.html로 이동하게 수정
  js/tokenValid.js
  js/tokenValid.ts
Labels: 🛠FIX, 🟢LOW

#195 Design: common.css 속성 순서 정렬
  styles/components/_common.scss
  styles/main.css
  styles/pages/search.css
  styles/pages/searchResult.css
Labels: 🟢LOW, 🎨DESIGN

#189 Refactor: 차트페이지 예외처리 추가 및 코드정리
  js/chart2.js
  js/chart2.ts
Labels: 🧹REFACTOR, 🟢LOW

#198 Design: 나의감상문 헤더 height 적용
  styles/main.css
Labels: 🟢LOW, 🎨DESIGN

#200 Rename: chart2 -> chart로 파일명 수정
  js/chart.js
  js/chart.ts
  pages/chart.html
  styles/pages/myPage.css
  styles/pages/review.css
  styles/pages/writePost.css
Labels: 🟢LOW, ♻RENAME

#199 Design: writePost.scss 속성 순서 정렬
  styles/pages/writePost.scss
Labels: 🟢LOW, 🎨DESIGN

#201 Fix: 앨범에서 이미지가 없는 경우 기본 이미지가 보이도록 수정
  js/myPage.js
  js/myPage.ts
  styles/pages/myPage.scss
Labels: 🛠FIX, 🟡MEDIUM, 🎨DESIGN

#203 Feature: 회원가입 완료 후 로그인 이동 페이지
  pages/moveLogin.html
  styles/pages/login.css
  styles/pages/login.scss
Labels: 💡FEAT, 🟡MEDIUM, 🎨DESIGN

#204 Fix: html 코드 정리
  html/common.html
  html/modal.html
  index.html
  pages/chart.html
  pages/login.html
  pages/myPage.html
  pages/notFound.html
  pages/profileEdit.html
  pages/review.html
  pages/reviewDetail.html
  pages/reviewEdit.html
  pages/search.html
  pages/searchResult.html
  pages/signUp.html
  pages/writePost.html
Labels: 🛠FIX, 🟢LOW

#206 Style: css 속성 순서 변경
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 🟢LOW

#207 Design: 반응형 검색창 크기 조절 및 css 순서 정리
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🟢LOW, 🎨DESIGN

#208 Style: searchResult 순서 정리
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: 🟢LOW

#210 Feature/search 무한스크롤
  js/movieApi.js
  js/movieApi.ts
  js/search.js
  js/search.ts
Labels: 💡FEAT, 🟡MEDIUM

#211 Feature/search 페이지 말줄임 word-break 제거
  pages/search.html
  styles/pages/search.css
  styles/pages/search.scss
Labels: 🟡MEDIUM, 🎨DESIGN

#213 Style: CSS 속성 순서 컨벤션에 맞게 변경
  styles/components/_buttons.scss
  styles/components/_card.scss
  styles/components/_modal.scss
  styles/main.css
  styles/pages/home.css
  styles/pages/home.scss
  styles/pages/login.css
  styles/pages/login.scss
  styles/pages/signUp.css
  styles/pages/signUp.scss
Labels: 🟢LOW

#216 Feature: 회원가입시 페이지이동 및 회원가입 버그 수정
  js/moveLogin.js
  js/moveLogin.ts
  js/signUp.js
  js/signUp.ts
  pages/moveLogin.html
  pages/signUp.html
Labels: 🛠FIX, 🟢LOW

#218 Style: CSS 속성 순서 컨벤션에 맞게 변경
  styles/pages/review.css
  styles/pages/review.scss
  styles/pages/reviewDetail.css
  styles/pages/reviewDetail.scss
Labels: 🧹REFACTOR, 🟢LOW

#217 Feature: 포스터 클릭 시 검색결과페이지로 이동
  js/randomMovie.js
  js/randomMovie.ts
  styles/components/_common.scss
  styles/main.css
  styles/pages/home.css
  styles/pages/home.scss
Labels: 💡FEAT, 🟢LOW

#219 Design: 포스터 이미지 크기 이상 현상 해결(이슈 #215)
  styles/pages/searchResult.css
  styles/pages/searchResult.scss
Labels: ☠BUG, 🎨DESIGN

#221 Feature: 검색어와 일치 시 하이라이트 표시
  js/search.js
  js/search.ts
Labels: 💡FEAT, 🟢LOW

#223 Style: CSS 속성 순서 변경, 불필요한 코드 제거
  index.html
  pages/searchResult.html
  styles/components/_card.scss
  styles/components/_common.scss
  styles/main.css
  styles/pages/home.css
  styles/pages/home.scss
Labels: 🟢LOW

#230 movieListInterface 정리 및 적용
  js/movieListInterface.ts
  js/search.ts
  js/searchResult.js
  js/searchResult.ts
Labels: 🧹REFACTOR, 🟢LOW

#222 Fix: 마이페이지 리뷰 더 불러오기
  js/myPage.js
  js/myPage.ts
Labels: 🛠FIX, 🟡MEDIUM

#225 Fix: 로그인 필요한 페이지에서 로그인 시 해당 페이지로 이동
  js/login.js
  js/login.ts
  js/myPage.js
  js/myPage.ts
  js/review.js
  js/review.ts
  js/tokenValid.js
  js/tokenValid.ts
Labels: 🛠FIX, 🟢LOW

#232 Feature: 404 페이지 구현
  js/chart.js
  js/chart.ts
  js/movieApi.js
  js/movieApi.ts
  js/reviewApi.js
  js/reviewApi.ts
  js/searchResult.js
  js/searchResult.ts
  pages/notFound.html
Labels: 💡FEAT, 🟡MEDIUM

#234 Style: 콘솔 제거 및 파일명 수정
  js/boxOfficeApi.js
  js/boxOfficeApi.ts
  js/reviewDetail.js
  js/reviewDetail.ts
  js/signUp.js
  js/signUp.ts
  styles/components/_modal.scss
  styles/main.css
Labels: 🟢LOW, 🎨DESIGN, ♻RENAME

#236 Fix: 랜덤 영화 리스트 추가
  js/randomMovie.js
  js/randomMovie.ts
  js/randomMovieList.js
  js/randomMovieList.ts
Labels: 🟢LOW

#235 Fix: 차트페이지 에러문구 수정 및 영화제목요청시 공백 제거, line-height 수정
  js/chart.js
  js/chart.ts
  styles/pages/chart.css
  styles/pages/chart.scss
Labels: 📡API, 🛠FIX, 🟡MEDIUM

#233 Fix: 영화 검색 결과 보여주는 순서 변경
  js/movieApi.js
  js/movieApi.ts
  js/search.js
  js/search.ts
Labels: 🛠FIX, 🟢LOW

#238 Fix: 리뷰목록 없을때 감상문 작성 클릭 시 영화검색 페이지로 이동
  js/review.js
  js/review.ts
Labels: 🛠FIX, 🟢LOW

#239 Fix: 같은 제목으로 검색 시 항목 계속 추가되는 버그 수정
  js/search.js
  js/search.ts
Labels: 🛠FIX, 🔴HIGH

#241 Fix: js 파일 경로 수정
  index.html
  js/pages/chart.js
  js/pages/chart.ts
  js/pages/home.js
  js/pages/login.js
  js/pages/myPage.js
  js/pages/profileEdit.js
  js/pages/randomMovie.js
  js/pages/review.js
  js/pages/review.ts
  js/pages/reviewDetail.js
  js/pages/reviewEdit.js
  js/pages/search.js
  js/pages/search.ts
  js/pages/searchResult.js
  js/pages/searchResult.ts
  js/pages/signUp.js
  js/pages/writePost.js
  js/pages/writePost.ts
  pages/chart.html
  pages/login.html
  pages/moveLogin.html
  pages/myPage.html
  pages/profileEdit.html
  pages/review.html
  pages/reviewDetail.html
  pages/reviewEdit.html
  pages/search.html
  pages/searchResult.html
  pages/signUp.html
  pages/writePost.html
Labels: ☠BUG, 🛠FIX, 🔴HIGH
